version: '3.8'

services:
  example-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - valkey
    environment:
        VALKEY_HOST: valkey:6379
        USE_VALKEY: true

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"